# travis rules for project
language: cpp
compiler:
  - gcc

before_install:
  # install deps
  - sudo apt-get install -y  libopencv-dev  libopenni-dev  libgtest-dev  libboost-dev  libboost-filesystem-dev

script: # compile
  - mkdir build
  - cd build
  - cmake ..
  - make
